create table if not exists public.stock_movements (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  sku text not null default '',
  category_name text not null default 'Otros',
  movement_type text not null check (movement_type in ('entry', 'sale', 'adjustment', 'return')),
  quantity_delta integer not null check (quantity_delta <> 0),
  stock_before integer not null check (stock_before >= 0),
  stock_after integer not null check (stock_after >= 0),
  note text not null default '',
  actor_label text not null default 'Usuario',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists stock_movements_created_at_idx on public.stock_movements (created_at desc);
create index if not exists stock_movements_product_id_idx on public.stock_movements (product_id, created_at desc);

alter table public.stock_movements enable row level security;
drop policy if exists "Admins read stock movements" on public.stock_movements;
create policy "Admins read stock movements" on public.stock_movements
for select to authenticated
using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));

create or replace function public.log_product_stock_change()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  previous_stock integer;
  movement_delta integer;
  movement_kind text;
  category_label text;
  user_label text;
  movement_note text;
begin
  if tg_op = 'INSERT' then
    previous_stock := 0;
    movement_delta := new.stock;
    if movement_delta = 0 then return new; end if;
    movement_kind := 'entry';
  else
    if old.stock is not distinct from new.stock then return new; end if;
    previous_stock := old.stock;
    movement_delta := new.stock - old.stock;
    movement_kind := coalesce(nullif(current_setting('app.stock_movement_type', true), ''), case when movement_delta > 0 then 'entry' else 'adjustment' end);
  end if;

  select name into category_label from public.categories where id = new.category_id;
  select coalesce(nullif(full_name, ''), 'Usuario') into user_label from public.profiles where id = auth.uid();
  movement_note := coalesce(nullif(current_setting('app.stock_movement_note', true), ''), '');

  insert into public.stock_movements (
    product_id, product_name, sku, category_name, movement_type, quantity_delta,
    stock_before, stock_after, note, actor_label, created_by
  ) values (
    new.id, new.name, new.sku, coalesce(category_label, 'Otros'), movement_kind, movement_delta,
    previous_stock, new.stock, movement_note, coalesce(user_label, 'Usuario'), auth.uid()
  );
  return new;
end;
$$;

drop trigger if exists products_log_stock_change on public.products;
create trigger products_log_stock_change
after insert or update of stock on public.products
for each row execute function public.log_product_stock_change();

create or replace function public.record_stock_change(
  p_product_id bigint,
  p_delta integer,
  p_movement_type text,
  p_note text default ''
)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  if not exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') then
    raise exception 'Only administrators can change stock';
  end if;
  if p_delta = 0 then raise exception 'Movement quantity cannot be zero'; end if;
  if p_movement_type not in ('entry', 'adjustment', 'return') then raise exception 'Invalid stock movement type'; end if;
  if p_movement_type in ('entry', 'return') and p_delta < 0 then raise exception 'Entries and returns must increase stock'; end if;

  perform set_config('app.stock_movement_type', p_movement_type, true);
  perform set_config('app.stock_movement_note', coalesce(p_note, ''), true);
  update public.products
  set stock = stock + p_delta
  where id = p_product_id and stock + p_delta >= 0;
  if not found then raise exception 'Product not found or stock cannot be negative'; end if;
end;
$$;

create or replace function public.create_sale(items jsonb)
returns bigint
language plpgsql
security definer set search_path = public
as $$
declare
  new_sale_id bigint;
  item jsonb;
  product_record public.products%rowtype;
  sale_total numeric(10,2) := 0;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;

  for item in
    select jsonb_build_object('product_id', grouped.product_id, 'quantity', grouped.quantity)
    from (
      select product_id, sum(quantity)::integer as quantity
      from jsonb_to_recordset(items) as line(product_id bigint, quantity integer)
      group by product_id
    ) as grouped
  loop
    if (item->>'quantity')::integer <= 0 then raise exception 'Sale quantity must be positive'; end if;
    select * into product_record from public.products where id = (item->>'product_id')::bigint for update;
    if product_record.id is null or product_record.stock < (item->>'quantity')::integer then raise exception 'Insufficient stock'; end if;
    sale_total := sale_total + product_record.price * (item->>'quantity')::integer;
  end loop;

  insert into public.sales (seller_id, total) values (auth.uid(), sale_total) returning id into new_sale_id;
  perform set_config('app.stock_movement_type', 'sale', true);
  perform set_config('app.stock_movement_note', 'Venta #' || new_sale_id, true);
  for item in
    select jsonb_build_object('product_id', grouped.product_id, 'quantity', grouped.quantity)
    from (
      select product_id, sum(quantity)::integer as quantity
      from jsonb_to_recordset(items) as line(product_id bigint, quantity integer)
      group by product_id
    ) as grouped
  loop
    select * into product_record from public.products where id = (item->>'product_id')::bigint;
    insert into public.sale_items (sale_id, product_id, quantity, unit_price)
    values (new_sale_id, product_record.id, (item->>'quantity')::integer, product_record.price);
    update public.products set stock = stock - (item->>'quantity')::integer where id = product_record.id;
  end loop;
  return new_sale_id;
end;
$$;

revoke all on function public.record_stock_change(bigint, integer, text, text) from public;
revoke all on function public.record_stock_change(bigint, integer, text, text) from anon;
revoke all on function public.create_sale(jsonb) from public;
revoke all on function public.create_sale(jsonb) from anon;
grant execute on function public.record_stock_change(bigint, integer, text, text) to authenticated;
grant execute on function public.create_sale(jsonb) to authenticated;