create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role text not null default 'seller' check (role in ('admin', 'seller')),
  created_at timestamptz not null default now()
);

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text not null unique,
  category_id bigint references public.categories(id),
  price numeric(10,2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  min_stock integer not null default 0 check (min_stock >= 0),
  created_at timestamptz not null default now()
);

create table public.sales (
  id bigint generated by default as identity primary key,
  seller_id uuid not null references public.profiles(id),
  total numeric(10,2) not null check (total >= 0),
  created_at timestamptz not null default now()
);

create table public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null check (quantity > 0),
  unit_price numeric(10,2) not null check (unit_price >= 0)
);

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;

create policy "Users can read their profile" on public.profiles for select using (auth.uid() = id);
create policy "Authenticated users can read catalog" on public.categories for select to authenticated using (true);
create policy "Authenticated users can read products" on public.products for select to authenticated using (true);
create policy "Admins manage categories" on public.categories for all to authenticated using ((select role from public.profiles where id = auth.uid()) = 'admin') with check ((select role from public.profiles where id = auth.uid()) = 'admin');
create policy "Admins manage products" on public.products for all to authenticated using ((select role from public.profiles where id = auth.uid()) = 'admin') with check ((select role from public.profiles where id = auth.uid()) = 'admin');
create policy "Users read sales" on public.sales for select to authenticated using (seller_id = auth.uid() or (select role from public.profiles where id = auth.uid()) = 'admin');
create policy "Sellers create sales" on public.sales for insert to authenticated with check (seller_id = auth.uid());
create policy "Users read sale items" on public.sale_items for select to authenticated using (exists (select 1 from public.sales where sales.id = sale_id and (sales.seller_id = auth.uid() or (select role from public.profiles where id = auth.uid()) = 'admin')));
create policy "Sellers create sale items" on public.sale_items for insert to authenticated with check (exists (select 1 from public.sales where sales.id = sale_id and sales.seller_id = auth.uid()));

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''), 'seller');
  return new;
end;
$$;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();